import './globals.css'
import { Inter } from 'next/font/google'
import Navbar from '@/components/navbar'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Gordillo Ulises ',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel='stylesheet' href='https://bootswatch.com/5/lux/bootstrap.min.css'></link>
      </head>
      <body className={inter.className}>
        <Navbar />
        <div className="container p-4"> 
          {children}
        </div>
      </body>
    </html>
  )
}
